In [1]:
import numpy as np
import agent as a
from consts import *

In [2]:
## WORLD
## 0 is a normal state
## 1 is a positive goal state
## 2 is a negative goal state
## 3 is unpathable obstacle
world_state = [[0 for col in range(COLS)] for row in range(ROWS)]
world_state[1][3] = POS_GOAL
world_state[2][3] = NEG_GOAL
world_state[1][1] = NO_PATH
world_state = np.array(world_state)

In [3]:
## REWARD_FN
reward_fn = [[-0.04 for col in range(COLS)] for row in range(ROWS)]
reward_fn[1][3] = NEG_REW
reward_fn[2][3] = POS_REW
reward_fn = np.array(reward_fn)

In [4]:
print(reward_fn)

[[-0.04 -0.04 -0.04 -0.04]
 [-0.04 -0.04 -0.04 -1.  ]
 [-0.04 -0.04 -0.04  1.  ]]


In [5]:
## POLICY
policy = [[DOWN for col in range(COLS)] for row in range(ROWS)]
policy[2][0] = RIGHT
policy[0][1] = LEFT
policy[1][1] = NO_POL
policy[2][1] = RIGHT
policy[0][2] = LEFT
policy[2][2] = RIGHT
policy[0][3] = LEFT
policy[1][3] = NO_POL
policy[2][3] = NO_POL
policy = np.array(policy)

In [6]:
print(policy)

[[1 2 2 2]
 [1 4 1 4]
 [3 3 3 4]]


In [7]:
my_agent = a.Agent(world_state, reward_fn, policy)

In [8]:
for i in range(50000):
    my_agent.act()

In [9]:
my_agent.values

array([[ 0.70530222,  0.6552178 , -0.04      , -0.04      ],
       [ 0.76154556,  0.        ,  0.65510285, -1.        ],
       [ 0.81172845,  0.86703259,  0.91717821,  1.        ]])